dist: xenial
addons:
  sonarcloud:
    organization: "gimpneek-github"
    token:
      secure: $SONARQUBE_TOKEN
services:
  - docker
language: python
python:
  - 3.7
install:
  - make install_bot_deps
script:
  - make ci_test
  - docker build -t $IMAGE_REPO_URL:$TRAVIS_TAG  -t $IMAGE_REPO_URL:latest .
  - DISCORD_KEY=$DISCORD_KEY pytest docker
before_deploy:
  - make install_aws
  - make install_ecs_deps
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    tags: true