dist: xenial
addons:
  sonarcloud:
    organization: "gimpneek-github"
    token:
      secure: $SONARQUBE_TOKEN
services:
  - docker
language: python
python:
  - 3.7
install:
  - make install_bot_deps
script:
  - make ci_test
  - make install_aws
  - make install_ecs_deps
before_deploy:
  - make install_aws
  - make install_ecs_deps
deploy:
  provider: script
  script: make deploy
  on:
    tags: true