addons:
  sonarcloud:
    organization: "gimpneek-github"
    token:
      secure: $SONARQUBE_TOKEN
services:
  - docker
language: python
python:
  - 3.7
script:
  - nosetests
  - sonar-scanner
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    tags: true